### ISSUE TITLE
Ruutu plugin not working

### ISSUE THREAD

**Issue by uke75** [Dis90/plugin.video.ruutu#1]
Can't start the plugin, I'm getting following error:

> 2020-07-16 13:29:13.893 T:139753532118784   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                           - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                          Error Contents: No JSON object could be decoded
                                          Traceback (most recent call last):
                                             File "/home/kodi/.kodi/addons/plugin.video.ruutu/addon.py", line 555, in <module>
                                                router(sys.argv[2][1:])
                                              File "/home/kodi/.kodi/addons/plugin.video.ruutu/addon.py", line 544, in router
                                                helper.login_process()
                                              File "/home/kodi/.kodi/addons/plugin.video.ruutu/resources/lib/kodihelper.py", line 118, in login_process
                                                self.r.login(username, password)
                                             File "/home/kodi/.kodi/addons/plugin.video.ruutu/resources/lib/ruutu.py", line 155, in login
                                                login_page_json = json.loads(data)
                                              File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
                                                return _default_decoder.decode(s)
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                                raise ValueError("No JSON object could be decoded")
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--

With the software versions:
 Kodi 2:18.7+git20200520.1011-final-0bionic.1~ 
 Python 2.7.17

Is there a fix for this?

Thanks

**Comment by Dis90** [comment]
Addon is no longer maintained. So there is no fix for this.

**Comment by uke75** [comment]
Oh blimey, would be nice to have a working Ruutu+ plugin.
